updated file

diff --git a/Jenkinsfile-ansible b/Jenkinsfile-ansible
--- a/Jenkinsfile-ansible
+++ b/Jenkinsfile-ansible
@@ -41,14 +41,15 @@ pipeline {
                 container('ansible') {
                 sh '''
                 echo "Installing system dependencies..."
-                apk add --no-cache gcc python3-dev build-base musl-dev openssl-dev cmake make gcc g++ linux-headers || { echo "Failed to install system dependencies"; exit 1; }
+                apk add --no-cache gcc python3.10 python3.10-venv python3-dev build-base musl-dev openssl-dev cmake make gcc g++ linux-headers || { echo "Failed to install system dependencies"; exit 1; }
                 
                 echo "Upgrading pip..."
                 pip install --upgrade pip || { echo "Failed to upgrade pip"; exit 1; }
                 echo "Uninstalling any existing Azure CLI versions..."
                 echo "Creating and activating a virtual environment..."
-                python3 -m venv /opt/ansible-venv || { echo "Failed to create virtual environment"; exit 1; }
-                source /opt/ansible-venv/bin/activate
+                python3.10 -m venv ansible-venv
+                source ansible-venv/bin/activate
+                pip install ansible uamqp
                 pip install --no-cache-dir uamqp
                 pip install --upgrade pip setuptools wheel
                 echo "Installing msgraph2..."
