updated files

diff --git a/Jenkinsfile-7 b/Jenkinsfile-7
--- a/Jenkinsfile-7
+++ b/Jenkinsfile-7
@@ -90,8 +90,25 @@ pipeline {
             steps {
                 container('terraform') {
                     sh '''
-                    az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
-                    az account set --subscription $ARM_SUBSCRIPTION_ID
+                    if ! command -v az &> /dev/null; then
+                        echo "Azure CLI not found. Installing..."
+                        apk add --no-cache curl bash jq sudo py3-pip python3-dev gcc musl-dev libffi-dev
+                        python3 -m pip install --upgrade pip setuptools wheel
+                        pip install azure-cli
+                    else
+                        echo "Azure CLI is already installed."
+                    fi
+                    az --version
+                    '''
+                    script {
+                        withCredentials([azureServicePrincipal('Azure_SP_ID')]) {
+                            sh '''
+                            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
+                            az account set --subscription $ARM_SUBSCRIPTION_ID
+                            '''
+                        }
+                    }
+                    sh '''
                     cd ./05-learning
                     terraform plan -out=tfplan
                     '''
