updated file

diff --git a/Jenkinsfile-ansible b/Jenkinsfile-ansible
--- a/Jenkinsfile-ansible
+++ b/Jenkinsfile-ansible
@@ -99,6 +99,16 @@ pipeline {
         stage('Run Ansible Playbook') {
             steps {
                 container('ansible') {
+                    sh '''
+                    if ! command -v az &> /dev/null; then
+                        echo "Azure CLI not found. Installing..."
+                        apk add --no-cache curl bash jq sudo py3-pip python3-dev gcc musl-dev libffi-dev
+                        python3 -m pip install --upgrade pip setuptools wheel
+                        pip install azure-cli
+                    else
+                        echo "Azure CLI is already installed."
+                    fi
+                    '''
                     script {
                         withCredentials([azureServicePrincipal('Terraform_Secret_ID')]) {
                             sh '''
