updated

diff --git a/Jenkinsfile-7 b/Jenkinsfile-7
--- a/Jenkinsfile-7
+++ b/Jenkinsfile-7
@@ -1,23 +1,23 @@
 pipeline {
-    agent {
-        kubernetes {
-            yaml '''
-            apiVersion: v1
-            kind: Pod
-            spec:
-              containers:
-              - name: terraform
-                image: hashicorp/terraform:latest
-                command: [ "sleep" ]
-                args: [ "infinity" ]
-              - name: azure-cli
-                image: mcr.microsoft.com/azure-cli
-                command: [ "sleep" ]
-                args: [ "infinity" ]
-            '''
-        }
-    }
-
+    // agent {
+    //     kubernetes {
+    //         yaml '''
+    //         apiVersion: v1
+    //         kind: Pod
+    //         spec:
+    //           containers:
+    //           - name: terraform
+    //             image: hashicorp/terraform:latest
+    //             command: [ "sleep" ]
+    //             args: [ "infinity" ]
+    //           - name: azure-cli
+    //             image: mcr.microsoft.com/azure-cli
+    //             command: [ "sleep" ]
+    //             args: [ "infinity" ]
+    //         '''
+    //     }
+    // }
+    agent none
     environment {
         ARM_SUBSCRIPTION_ID = credentials('AZURE_SUBSCRIPTION_ID')
     }
@@ -28,10 +28,20 @@ pipeline {
                 checkout scm
             }
         }
-
+        stage('Installation of tools') {
+            agent {
+                docker { 
+                    image 'vakem/kubepodtemplate:latest'
+                    args '--user root'
+                }
+            }
+            steps {
+                sh 'az --version'
+            }
+        }
         stage('Install Terraform & Azure CLI if not installed') {
             steps {
-                container('terraform') {
+                container('docker') {
                     sh '''
                     if ! command -v terraform &> /dev/null; then
                         echo "Terraform not found. Installing..."
@@ -42,51 +52,52 @@ pipeline {
                     '''
                 }
 
-                container('azure-cli') {
-                    sh '''
-                    if ! command -v az &> /dev/null; then
-                        echo "Azure CLI not found. Installing..."
-                        apk add --no-cache curl bash jq sudo py3-pip python3-dev gcc musl-dev libffi-dev
-                        python3 -m pip install --upgrade pip setuptools wheel
-                        pip install azure-cli
-                    else
-                        echo "Azure CLI is already installed."
-                    fi
-                    '''
+                container('docker') {
+                    // sh '''
+                    // if ! command -v az &> /dev/null; then
+                    //     echo "Azure CLI not found. Installing..."
+                    //     apk add --no-cache curl bash jq sudo py3-pip python3-dev gcc musl-dev libffi-dev
+                    //     python3 -m pip install --upgrade pip setuptools wheel
+                    //     pip install azure-cli
+                    // else
+                    //     echo "Azure CLI is already installed."
+                    // fi
+                    // '''
+                    sh 'az --version'
                 }
             }
         }
 
         stage('Azure Login') {
             steps {
-                container('azure-cli') {
+                container('docker') {
                      // Install Python if it is not available
-                    sh '''
-                    if ! command -v python3 &> /dev/null
-                    then
-                        echo "Python3 could not be found. Installing..."
-                        apk add --no-cache python3 py3-pip
-                    else
-                        echo "Python3 is already installed"
-                    fi
+                    // sh '''
+                    // if ! command -v python3 &> /dev/null
+                    // then
+                    //     echo "Python3 could not be found. Installing..."
+                    //     apk add --no-cache python3 py3-pip
+                    // else
+                    //     echo "Python3 is already installed"
+                    // fi
                     
-                    # Install pip manually if not available
-                    if ! python3 -m pip --version &> /dev/null
-                    then
-                        echo "pip could not be found. Installing..."
-                        python3 -m ensurepip --upgrade
-                    else
-                        echo "pip is already installed"
-                    fi
+                    // # Install pip manually if not available
+                    // if ! python3 -m pip --version &> /dev/null
+                    // then
+                    //     echo "pip could not be found. Installing..."
+                    //     python3 -m ensurepip --upgrade
+                    // else
+                    //     echo "pip is already installed"
+                    // fi
                     
-                    # Upgrade pip, setuptools, and wheel
-                    python3 -m pip install --upgrade pip setuptools wheel
-                    '''
+                    // # Upgrade pip, setuptools, and wheel
+                    // python3 -m pip install --upgrade pip setuptools wheel
+                    // '''
                     sh '''
                     az --version
                     '''
                     script {
-                        withCredentials([azureServicePrincipal('Terraform_Secret_ID')]) {
+                        withCredentials([azureServicePrincipal('AZURE_SUBSCRIPTION_ID')]) {
                             sh '''
                             az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
                             az account set --subscription $ARM_SUBSCRIPTION_ID
@@ -99,7 +110,7 @@ pipeline {
 
         stage('Terraform Init') {
             steps {
-                container('terraform') {
+                container('docker') {
                     sh '''
                     cd ./05-learning
                     terraform init
@@ -110,56 +121,55 @@ pipeline {
 
         stage('Terraform Plan') {
             steps {
-                container('azure-cli') {
-                    sh '''
-                    if ! command -v az &> /dev/null; then
-                        echo "Azure CLI not found. Installing..."
-                        apk add --no-cache curl bash jq sudo py3-pip python3-dev gcc musl-dev libffi-dev
-                        python3 -m pip install --upgrade pip setuptools wheel
-                        pip install azure-cli
-                    else
-                        echo "Azure CLI is already installed."
-                    fi
-                    '''
+                container('docker') {
+                    // sh '''
+                    // if ! command -v az &> /dev/null; then
+                    //     echo "Azure CLI not found. Installing..."
+                    //     apk add --no-cache curl bash jq sudo py3-pip python3-dev gcc musl-dev libffi-dev
+                    //     python3 -m pip install --upgrade pip setuptools wheel
+                    //     pip install azure-cli
+                    // else
+                    //     echo "Azure CLI is already installed."
+                    // fi
+                    // '''
                     script {
-                        withCredentials([azureServicePrincipal('Terraform_Secret_ID')]) {
+                        withCredentials([azureServicePrincipal('AZURE_SUBSCRIPTION_ID')]) {
                             sh '''
                             az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
                             az account show
-                            az group list --query "[?location=='eastus']"
                             '''
                         }
                     }
                 }
 
-                container('terraform') {
+                container('docker') {
                     //   apk add --no-cache curl bash jq unzip python3 py3-pip
                     // apk add --no-cache gcc python3-dev musl-dev linux-headers
                     // pip install --break-system-packages psutil
                     // pip install --break-system-packages azure-cli
                     // az version  # Verify installation
-                    sh '''
+                    // sh '''
                   
 
-                    # Install only if not already installed
-                    if ! command -v curl >/dev/null 2>&1; then apk add --no-cache curl; fi
-                    if ! command -v bash >/dev/null 2>&1; then apk add --no-cache bash; fi
-                    if ! command -v jq >/dev/null 2>&1; then apk add --no-cache jq; fi
-                    if ! command -v unzip >/dev/null 2>&1; then apk add --no-cache unzip; fi
-                    if ! command -v python3 >/dev/null 2>&1; then apk add --no-cache python3 py3-pip; fi
+                    // # Install only if not already installed
+                    // if ! command -v curl >/dev/null 2>&1; then apk add --no-cache curl; fi
+                    // if ! command -v bash >/dev/null 2>&1; then apk add --no-cache bash; fi
+                    // if ! command -v jq >/dev/null 2>&1; then apk add --no-cache jq; fi
+                    // if ! command -v unzip >/dev/null 2>&1; then apk add --no-cache unzip; fi
+                    // if ! command -v python3 >/dev/null 2>&1; then apk add --no-cache python3 py3-pip; fi
 
-                    # Check if GCC and other dependencies are installed before installing
-                    if ! command -v gcc >/dev/null 2>&1; then apk add --no-cache gcc python3-dev musl-dev linux-headers; fi
+                    // # Check if GCC and other dependencies are installed before installing
+                    // if ! command -v gcc >/dev/null 2>&1; then apk add --no-cache gcc python3-dev musl-dev linux-headers; fi
 
-                    # Install pip packages only if not installed
-                    if ! python3 -c "import psutil" >/dev/null 2>&1; then pip install --break-system-packages psutil; fi
-                    if ! command -v az >/dev/null 2>&1; then pip install --break-system-packages azure-cli; fi
+                    // # Install pip packages only if not installed
+                    // if ! python3 -c "import psutil" >/dev/null 2>&1; then pip install --break-system-packages psutil; fi
+                    // if ! command -v az >/dev/null 2>&1; then pip install --break-system-packages azure-cli; fi
 
-                    # Verify Azure CLI installation updated
-                    az version
-                    '''
+                    // # Verify Azure CLI installation updated
+                    // az version
+                    // '''
                     script {
-                        withCredentials([azureServicePrincipal('Terraform_Secret_ID')]) {
+                        withCredentials([azureServicePrincipal('AZURE_SUBSCRIPTION_ID')]) {
                             sh '''
                             az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
                             '''
@@ -175,7 +185,7 @@ pipeline {
 
         stage('Terraform Apply') {
             steps {
-                container('terraform') {
+                container('docker') {
                     sh '''
                     cd ./05-learning
                     terraform apply -auto-approve
@@ -187,7 +197,7 @@ pipeline {
 
     post {
         always {
-            container('azure-cli') {
+            container('docker') {
                 sh 'az logout'
             }
         }
