updated all

diff --git a/Jenkinsfile-ansible b/Jenkinsfile-ansible
--- a/Jenkinsfile-ansible
+++ b/Jenkinsfile-ansible
@@ -36,10 +36,26 @@ pipeline {
                 container('ansible') {
                     sh '''
                     apk update
-                    apk add --no-cache bash curl jq unzip python3 py3-pip
-                    pip install --no-cache-dir ansible
+                    if ! command -v az &> /dev/null; then
+                        echo "Azure CLI not found. Installing..."
+                        apk add --no-cache curl bash jq sudo python3 py3-pip  gcc musl-dev libffi-dev
+                        python3 -m pip install --upgrade pip setuptools wheel
+                        pip install --no-cache-dir ansible
+                        pip install azure-cli
+                    else
+                        echo "Azure CLI is already installed."
+                    fi
                     ansible --version  # Verify installation
                     '''
+                }
+                script {
+                    withCredentials([azureServicePrincipal('Terraform_Secret_ID')]) {
+                        sh '''
+                        az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
+                        az account show
+                        az group list --query "[?location=='eastus']"
+                        '''
+                    }
                 }
             }
         }
